### PR TITLE
Addressed issue #12

### PR DESCRIPTION
**Pull request by evelinec**
- Addressed Gilbert's review feedback issue #12

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
@andrewdes would you check the pom.xml file change?

**Comment by evelinec** [comment]
Yes, I'll iterate the finish/pom.xml to the start directory as well, once everything is good. @andrewdes the liberty-maven-parent plugin is not used for this guide, as it provides lots of redundancies that aren't necessary. It's also explained in #12. Thanks for reviewing.

**Comment by evelinec** [comment]
Re the image on this guide, see: the "sessionCache.png" image isn't showing up on the test site - pending on OpenLiberty/openliberty.io#935

**Comment by evelinec** [comment]
Re this point, the `hazelcast-config.xml` file is highlighted/pointed at when hover over the action arrow. Not sure what other highlight is needed. 

* Under the section "Configuring HazelCast", the action arrow "Create a new hazelcast-config.xml config file." does not highlight the hazelcast-config.xml file

**Comment by evelinec** [comment]
Others are fixed in the latest commit. @gkwan-ibm can you review again? Thanks.

**Pull request merged**
