### PR TITLE
Some Improvements about Hazelcast Session Guide

### PR DESCRIPTION
**Pull request by mesutcelik**
Hi,

I have gone through the guide. Overall, it was very smooth experience.  Thanks for the guide. 👏 

This is a small PR for some updates. You can take it partially or merge the full PR. 

- When I saw `make a POST request` on the guide but could not see an Curl then I realized that it was mentioning about UI. I added a clarification.
- Upgraded to latest hazelcast version 3.11.2
- removed password field. It is not needed for cluster formation[1] as of 3.8.2 and it is subject to be removed in future.[1],[2]
- Updated documentation to latest. `latest-dev` part in fact pointing to the dev version which is nightly snapshot.
- I added `verify hazelcast` part with some logs. I think that is important because if multicast has an issue then hazelcast will not be formed which would lead some failures in the guide.

[1] - https://docs.hazelcast.org/docs/latest/manual/html-single/#creating-cluster-groups
[2] - https://docs.hazelcast.org/docs/rn/index.html#behavioral-changes

### CODE REVIEW

**Comment by alexsm82** [comment]
Hi @mesutcelik, thanks for the contribution!  Before we can accept the PR we'll need either an Individual CLA or Corporate CLA.  The instructions for doing so are listed here: https://github.com/OpenLiberty/draft-guides-template under step 4, part 5.  Thanks!

**Comment by mesutcelik** [comment]
Hi @alexsm82 ,

I have submitted my individual CLA. Corporate CLA must also be submitted too by our legal. Let me know if it is not the case.

**Comment by alexsm82** [comment]
Thanks for sending in your CLA @mesutcelik!  The individual CLA is sufficient.

**Comment by evelinec** [comment]
@mesutcelik Thank you for the contribution. Merged.

**Pull request merged**
